name: project_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - app/**
  - package/**

scripts:
  analyze:
    exec: dart analyze
      
  test:
    run: melos exec -c 1  -- "flutter test --no-pub --coverage"

  clean:
    run: melos exec -c 1  -- "flutter clean"

  get:
    run: melos exec -c 1  -- "flutter pub get"
      
  outdated:
    run: melos exec -c 1  -- "flutter pub outdated"

  upgrade:
    run: melos exec -c 1  -- "flutter pub upgrade"