name: project_workspace

sdkPath: .fvm/flutter_sdk

packages:
  - app/**
  - package/**

scripts:
  analyze:
    exec: dart analyze
      
  test:
    exec: flutter test --no-pub --coverage

  get:
    exec: flutter pub get
      
  outdated:
    exec: flutter pub outdated

  upgrade:
    exec: flutter pub upgrade

  clean:
    exec: flutter clean

  doctor:
    exec: flutter doctor