name: project_workspace
description: Workspace for the project apps and realated packages

publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  fvm: ^3.1.0
  melos: ^6.0.0